/*
 * BoekVluchtFrame.java
 *
 * Created on June 12, 2008, 5:09 PM
 */

package userInterfaceLaag;

import domeinLaag.Luchthaven;
import domeinLaag.Vlucht;
import java.util.TreeMap;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author  Frank
 */
public class BoekVluchtFrame extends javax.swing.JFrame
{
	private BoekVluchtContr myController;
	private TreeMap<String, Luchthaven> luchthavens;
	private TreeMap<String, Vlucht> vluchten;
	
	/** Creates new form BoekVluchtFrame */
	public BoekVluchtFrame (BoekVluchtContr bvc)
	{
		this.myController = bvc;
		this.luchthavens = Luchthaven.geefAlle();
		this.vluchten = new TreeMap<String, Vlucht>();
		
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        vluchtPanel = new javax.swing.JPanel();
        vertrekpuntLabel = new javax.swing.JLabel();
        DefaultListCellRenderer lRenderer = new DefaultListCellRenderer();
        lRenderer.setHorizontalAlignment(DefaultListCellRenderer.CENTER);
        vertrekpuntComboBox = new javax.swing.JComboBox();
        bestemmingComboBox = new javax.swing.JComboBox();
        vertrekComboBox = new javax.swing.JComboBox();
        aankomstTextField = new javax.swing.JTextField();
        bestemmingLabel = new javax.swing.JLabel();
        vertrekLabel = new javax.swing.JLabel();
        aankomstLabel = new javax.swing.JLabel();
        vertrekTijdTextField = new javax.swing.JTextField();
        aankomstTijdTextField = new javax.swing.JTextField();
        naamTextField = new javax.swing.JTextField();
        straatTextField = new javax.swing.JTextField();
        stoelenTextField = new javax.swing.JTextField();
        huisNummerTextField = new javax.swing.JTextField();
        plaatsTextField = new javax.swing.JTextField();
        naamLabel = new javax.swing.JLabel();
        adresLabel = new javax.swing.JLabel();
        stoelenLabel = new javax.swing.JLabel();
        nietRokenButton = new javax.swing.JRadioButton();
        rokenButton = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vluchtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vlucht", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        vertrekpuntLabel.setText("Vertrekpunt");

        vertrekpuntComboBox.setRenderer(lRenderer);
        vertrekpuntComboBox.setModel(new javax.swing.DefaultComboBoxModel(luchthavens.keySet().toArray()));
        vertrekpuntComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertrekpuntComboBoxActionPerformed(evt);
            }
        });

        bestemmingComboBox.setRenderer(lRenderer);
        bestemmingComboBox.setModel(new javax.swing.DefaultComboBoxModel(luchthavens.keySet().toArray()));
        bestemmingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestemmingComboBoxActionPerformed(evt);
            }
        });

        vertrekComboBox.setRenderer(lRenderer);
        vertrekComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vertrekComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertrekComboBoxActionPerformed(evt);
            }
        });

        aankomstTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bestemmingLabel.setText("Bestemming");

        vertrekLabel.setText("Vertrek");

        aankomstLabel.setText("Aankomst");

        vertrekTijdTextField.setBackground(new java.awt.Color(255, 255, 255));
        vertrekTijdTextField.setEditable(false);
        vertrekTijdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vertrekTijdTextField.setText("tijd");

        aankomstTijdTextField.setBackground(new java.awt.Color(255, 255, 255));
        aankomstTijdTextField.setEditable(false);
        aankomstTijdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aankomstTijdTextField.setText("tijd");

        javax.swing.GroupLayout vluchtPanelLayout = new javax.swing.GroupLayout(vluchtPanel);
        vluchtPanel.setLayout(vluchtPanelLayout);
        vluchtPanelLayout.setHorizontalGroup(
            vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vluchtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vertrekpuntLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bestemmingLabel)
                    .addComponent(vertrekLabel)
                    .addComponent(aankomstLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vertrekComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bestemmingComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vertrekpuntComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 173, Short.MAX_VALUE))
                    .addComponent(aankomstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aankomstTijdTextField)
                    .addComponent(vertrekTijdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        vluchtPanelLayout.setVerticalGroup(
            vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vluchtPanelLayout.createSequentialGroup()
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vertrekpuntComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vertrekpuntLabel))
                .addGap(18, 18, 18)
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestemmingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bestemmingLabel))
                .addGap(18, 18, 18)
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vertrekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vertrekLabel)
                    .addComponent(vertrekTijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aankomstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aankomstLabel)
                    .addComponent(aankomstTijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        naamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        naamTextField.setText("N. Persoon");
        naamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naamTextFieldActionPerformed(evt);
            }
        });

        straatTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        straatTextField.setText("Straat");
        straatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straatTextFieldActionPerformed(evt);
            }
        });

        stoelenTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stoelenTextField.setText("2");
        stoelenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoelenTextFieldActionPerformed(evt);
            }
        });

        huisNummerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        huisNummerTextField.setText("00");
        huisNummerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huisNummerTextFieldActionPerformed(evt);
            }
        });

        plaatsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plaatsTextField.setText("Plaats");
        plaatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaatsTextFieldActionPerformed(evt);
            }
        });

        naamLabel.setText("Klant");

        adresLabel.setText("Adres");

        stoelenLabel.setText("Stoelen");

        buttonGroup1.add(nietRokenButton);
        nietRokenButton.setSelected(true);
        nietRokenButton.setText("Niet Roken");
        nietRokenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nietRokenButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rokenButton);
        rokenButton.setText("Roken");
        rokenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rokenButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(65, 23));
        okButton.setMinimumSize(new java.awt.Dimension(65, 23));
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naamLabel)
                            .addComponent(adresLabel)
                            .addComponent(stoelenLabel))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(straatTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naamTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(stoelenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nietRokenButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(huisNummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plaatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rokenButton)))
                    .addComponent(vluchtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vluchtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naamLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(straatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huisNummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plaatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stoelenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stoelenLabel)
                    .addComponent(nietRokenButton)
                    .addComponent(rokenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	private void vertrekpuntComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertrekpuntComboBoxActionPerformed
		Luchthaven vertrekpunt = luchthavens.get((String)vertrekpuntComboBox.getSelectedItem());
		Luchthaven bestemming = luchthavens.get((String)bestemmingComboBox.getSelectedItem());
		this.vluchten = myController.vertrekpuntEnBestemming(vertrekpunt, bestemming);
		
		vertrekComboBox.setModel(new javax.swing.DefaultComboBoxModel(vluchten.keySet().toArray()));
		aankomstTextField.setText(vluchten.firstEntry().getKey());
		
		SimpleDateFormat dagFormatter = new SimpleDateFormat("HH:mm");
		vertrekTijdTextField.setText(dagFormatter.format(vluchten.firstEntry().getValue().geefVertrekTijd().getTime()));
		aankomstTijdTextField.setText(dagFormatter.format(vluchten.firstEntry().getValue().getAankomstTijd().getTime()));
	}//GEN-LAST:event_vertrekpuntComboBoxActionPerformed

	private void bestemmingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestemmingComboBoxActionPerformed
		Luchthaven vertrekpunt = luchthavens.get((String)vertrekpuntComboBox.getSelectedItem());
		Luchthaven bestemming = luchthavens.get((String)bestemmingComboBox.getSelectedItem());
		this.vluchten = myController.vertrekpuntEnBestemming(vertrekpunt, bestemming);
		
		vertrekComboBox.setModel(new javax.swing.DefaultComboBoxModel(vluchten.keySet().toArray()));
		aankomstTextField.setText(vluchten.firstEntry().getKey());
		
		SimpleDateFormat dagFormatter = new SimpleDateFormat("HH:mm");
		vertrekTijdTextField.setText(dagFormatter.format(vluchten.firstEntry().getValue().geefVertrekTijd().getTime()));
		aankomstTijdTextField.setText(dagFormatter.format(vluchten.firstEntry().getValue().getAankomstTijd().getTime()));
	}//GEN-LAST:event_bestemmingComboBoxActionPerformed

	private void vertrekComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertrekComboBoxActionPerformed
		Vlucht vlucht = vluchten.get((String)vertrekComboBox.getSelectedItem());
		myController.vlucht(vlucht);

		SimpleDateFormat dagFormatter = new SimpleDateFormat("dd-MM-yy");
		aankomstTextField.setText(dagFormatter.format(vlucht.getAankomstTijd().getTime()));
		
		SimpleDateFormat tijdFormatter = new SimpleDateFormat("HH:mm");
		vertrekTijdTextField.setText(tijdFormatter.format(vluchten.firstEntry().getValue().geefVertrekTijd().getTime()));
		aankomstTijdTextField.setText(tijdFormatter.format(vluchten.firstEntry().getValue().getAankomstTijd().getTime()));
	}//GEN-LAST:event_vertrekComboBoxActionPerformed

	private void naamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naamTextFieldActionPerformed
		myController.klant(naamTextField.getText(), straatTextField.getText(), Integer.parseInt(huisNummerTextField.getText()), plaatsTextField.getText());
	}//GEN-LAST:event_naamTextFieldActionPerformed

	private void straatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straatTextFieldActionPerformed
		myController.klant(naamTextField.getText(), straatTextField.getText(), Integer.parseInt(huisNummerTextField.getText()), plaatsTextField.getText());
	}//GEN-LAST:event_straatTextFieldActionPerformed

	private void huisNummerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huisNummerTextFieldActionPerformed
		myController.klant(naamTextField.getText(), straatTextField.getText(), Integer.parseInt(huisNummerTextField.getText()), plaatsTextField.getText());
	}//GEN-LAST:event_huisNummerTextFieldActionPerformed

	private void plaatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaatsTextFieldActionPerformed
		myController.klant(naamTextField.getText(), straatTextField.getText(), Integer.parseInt(huisNummerTextField.getText()), plaatsTextField.getText());
	}//GEN-LAST:event_plaatsTextFieldActionPerformed

	private void stoelenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoelenTextFieldActionPerformed
		myController.plaats(Integer.parseInt(stoelenTextField.getText()), rokenButton.isSelected());
	}//GEN-LAST:event_stoelenTextFieldActionPerformed

	private void nietRokenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nietRokenButtonActionPerformed
		myController.plaats(Integer.parseInt(stoelenTextField.getText()), rokenButton.isSelected());
	}//GEN-LAST:event_nietRokenButtonActionPerformed

	private void rokenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rokenButtonActionPerformed
		myController.plaats(Integer.parseInt(stoelenTextField.getText()), rokenButton.isSelected());
	}//GEN-LAST:event_rokenButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		myController.ok();
	}//GEN-LAST:event_okButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		myController.cancel();
	}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aankomstLabel;
    private javax.swing.JTextField aankomstTextField;
    private javax.swing.JTextField aankomstTijdTextField;
    private javax.swing.JLabel adresLabel;
    private javax.swing.JComboBox bestemmingComboBox;
    private javax.swing.JLabel bestemmingLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField huisNummerTextField;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JTextField naamTextField;
    private javax.swing.JRadioButton nietRokenButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField plaatsTextField;
    private javax.swing.JRadioButton rokenButton;
    private javax.swing.JLabel stoelenLabel;
    private javax.swing.JTextField stoelenTextField;
    private javax.swing.JTextField straatTextField;
    private javax.swing.JComboBox vertrekComboBox;
    private javax.swing.JLabel vertrekLabel;
    private javax.swing.JTextField vertrekTijdTextField;
    private javax.swing.JComboBox vertrekpuntComboBox;
    private javax.swing.JLabel vertrekpuntLabel;
    private javax.swing.JPanel vluchtPanel;
    // End of variables declaration//GEN-END:variables
}
