/*
 * OvBkPerVlFrame.java
 *
 * Created on 11 juni 2008, 15:30
 */

package userInterfaceLaag;

/**
 *
 * @author  Bami
 */
public class OvBkPerVlFrame extends javax.swing.JFrame {

    /** Creates new form OvBkPerVlFrame */
    public OvBkPerVlFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

VluchtPanel = new javax.swing.JPanel();
vertrekPuntLabel = new javax.swing.JLabel();
bestemmingLabel = new javax.swing.JLabel();
vertrekLabel = new javax.swing.JLabel();
vertrekPuntComboBox = new javax.swing.JComboBox();
bestemmingPuntComboBox = new javax.swing.JComboBox();
vertrekComboBox = new javax.swing.JComboBox();
tijdTextField = new javax.swing.JTextField();
vluchtInfoPanel = new javax.swing.JPanel();
infoScrollPane = new javax.swing.JScrollPane();
infoTable = new javax.swing.JTable();
cancelButton = new javax.swing.JButton();
OKButton = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

VluchtPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
VluchtPanel.setToolTipText("");
VluchtPanel.setName(""); // NOI18N

vertrekPuntLabel.setText("Vetrekpunt");

bestemmingLabel.setText("Bestemming");

vertrekLabel.setText("Vertrek");

vertrekPuntComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

bestemmingPuntComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
bestemmingPuntComboBox.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
bestemmingPuntComboBoxActionPerformed(evt);
}
});

vertrekComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

tijdTextField.setText("jTextField1");

javax.swing.GroupLayout VluchtPanelLayout = new javax.swing.GroupLayout(VluchtPanel);
VluchtPanel.setLayout(VluchtPanelLayout);
VluchtPanelLayout.setHorizontalGroup(
VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(VluchtPanelLayout.createSequentialGroup()
.addContainerGap()
.addGroup(VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(vertrekPuntLabel)
.addComponent(bestemmingLabel)
.addComponent(vertrekLabel))
.addGap(84, 84, 84)
.addGroup(VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(vertrekComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(vertrekPuntComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(bestemmingPuntComboBox, 0, 193, Short.MAX_VALUE))
.addGap(52, 52, 52)
.addComponent(tijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(70, Short.MAX_VALUE))
);
VluchtPanelLayout.setVerticalGroup(
VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(VluchtPanelLayout.createSequentialGroup()
.addContainerGap()
.addGroup(VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(vertrekPuntLabel)
.addComponent(vertrekPuntComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(bestemmingLabel)
.addComponent(bestemmingPuntComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(VluchtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(vertrekLabel)
.addComponent(vertrekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(tijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(21, Short.MAX_VALUE))
);

vluchtInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

infoTable.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		
	},
	new String [] {
		"KLANT", "WOONPLAATS", "STOELEN", "ROKEN"
	}
));
infoScrollPane.setViewportView(infoTable);

javax.swing.GroupLayout vluchtInfoPanelLayout = new javax.swing.GroupLayout(vluchtInfoPanel);
vluchtInfoPanel.setLayout(vluchtInfoPanelLayout);
vluchtInfoPanelLayout.setHorizontalGroup(
vluchtInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(vluchtInfoPanelLayout.createSequentialGroup()
.addContainerGap()
.addComponent(infoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
.addContainerGap())
);
vluchtInfoPanelLayout.setVerticalGroup(
vluchtInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(vluchtInfoPanelLayout.createSequentialGroup()
.addContainerGap()
.addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);

cancelButton.setText("Cancel");
cancelButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
cancelButtonActionPerformed(evt);
}
});

OKButton.setText("OK");
OKButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
OKButtonActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(vluchtInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(VluchtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(cancelButton)))
.addContainerGap())
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(VluchtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(vluchtInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(cancelButton)
.addComponent(OKButton))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);

VluchtPanel.getAccessibleContext().setAccessibleName("");

pack();
}// </editor-fold>//GEN-END:initComponents

private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_OKButtonActionPerformed

private void bestemmingPuntComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestemmingPuntComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bestemmingPuntComboBoxActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OvBkPerVlFrame().setVisible(true);
            }
        });
    }

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton OKButton;
private javax.swing.JPanel VluchtPanel;
private javax.swing.JLabel bestemmingLabel;
private javax.swing.JComboBox bestemmingPuntComboBox;
private javax.swing.JButton cancelButton;
private javax.swing.JScrollPane infoScrollPane;
private javax.swing.JTable infoTable;
private javax.swing.JTextField tijdTextField;
private javax.swing.JComboBox vertrekComboBox;
private javax.swing.JLabel vertrekLabel;
private javax.swing.JComboBox vertrekPuntComboBox;
private javax.swing.JLabel vertrekPuntLabel;
private javax.swing.JPanel vluchtInfoPanel;
// End of variables declaration//GEN-END:variables

}
