
package userInterfaceLaag;

// Imports
import domeinLaag.Land;
import domeinLaag.LuchthavenException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class RegLuchthavenFrame extends JFrame
{
	// Relaties
	private RegLuchthavenContr myController;
	private TreeMap<String, Land> landen;

	// Constructors
	/** Creates new form RegLuchthavenFrame */
	public RegLuchthavenFrame (RegLuchthavenContr ctrl, TreeMap<String, Land> ln)
	{
		this.myController = ctrl;
		this.landen = ln;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jaNeeButtonGroup = new javax.swing.ButtonGroup();
        landLabel = new javax.swing.JLabel();
        landComboBox = new javax.swing.JComboBox();
        codeLabel = new javax.swing.JLabel();
        landCodeTextField = new javax.swing.JTextField();
        nieuweLuchthavenPanel = new javax.swing.JPanel();
        naamLabel = new javax.swing.JLabel();
        naamTextField = new javax.swing.JTextField();
        landCodeLabel = new javax.swing.JLabel();
        luchthavenCodeTextField = new javax.swing.JTextField();
        werkPlaatsLabel = new javax.swing.JLabel();
        jaButton = new javax.swing.JRadioButton();
        neeButton = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        landLabel.setText("Land");

        landComboBox.setModel(new javax.swing.DefaultComboBoxModel(landen.keySet().toArray()));
        landComboBox.setNextFocusableComponent(naamTextField);
        landComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landComboBoxActionPerformed(evt);
            }
        });

        codeLabel.setText("Code");

        landCodeTextField.setBackground(new java.awt.Color(240, 240, 240));
        landCodeTextField.setEditable(false);
        landCodeTextField.setFocusable(false);

        nieuweLuchthavenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nieuwe Luchthaven", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        naamLabel.setText("Naam");

        naamTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        naamTextField.setNextFocusableComponent(luchthavenCodeTextField);
        naamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naamTextFieldActionPerformed(evt);
            }
        });
        naamTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                naamTextFieldFocusLost(evt);
            }
        });

        landCodeLabel.setText("Code");

        luchthavenCodeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        luchthavenCodeTextField.setNextFocusableComponent(jaButton);
        luchthavenCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchthavenCodeTextFieldActionPerformed(evt);
            }
        });
        luchthavenCodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                luchthavenCodeTextFieldFocusLost(evt);
            }
        });

        werkPlaatsLabel.setText("Werkplaats");

        jaNeeButtonGroup.add(jaButton);
        jaButton.setText("Ja");
        jaButton.setNextFocusableComponent(okButton);
        jaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaButtonActionPerformed(evt);
            }
        });

        jaNeeButtonGroup.add(neeButton);
        neeButton.setSelected(true);
        neeButton.setText("Nee");
        neeButton.setNextFocusableComponent(okButton);
        neeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nieuweLuchthavenPanelLayout = new javax.swing.GroupLayout(nieuweLuchthavenPanel);
        nieuweLuchthavenPanel.setLayout(nieuweLuchthavenPanelLayout);
        nieuweLuchthavenPanelLayout.setHorizontalGroup(
            nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nieuweLuchthavenPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naamLabel)
                    .addComponent(landCodeLabel)
                    .addComponent(werkPlaatsLabel))
                .addGap(45, 45, 45)
                .addGroup(nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nieuweLuchthavenPanelLayout.createSequentialGroup()
                        .addComponent(jaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(neeButton))
                    .addComponent(luchthavenCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        nieuweLuchthavenPanelLayout.setVerticalGroup(
            nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nieuweLuchthavenPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamLabel)
                    .addComponent(naamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landCodeLabel)
                    .addComponent(luchthavenCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nieuweLuchthavenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(werkPlaatsLabel)
                    .addComponent(jaButton)
                    .addComponent(neeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        naamTextField.getAccessibleContext().setAccessibleDescription("Naam van de te registreren luchthaven");
        luchthavenCodeTextField.getAccessibleContext().setAccessibleDescription("Code voor de te registreren luchthaven");
        jaButton.getAccessibleContext().setAccessibleDescription("De te registreren luchthaven beschikt over een werkplaats");
        neeButton.getAccessibleContext().setAccessibleDescription("De te registreren luchthaven beschikt niet over een werkplaats");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(65, 23));
        okButton.setMinimumSize(new java.awt.Dimension(65, 23));
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nieuweLuchthavenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(landLabel)
                                .addGap(80, 80, 80)
                                .addComponent(landComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(codeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landLabel)
                    .addComponent(landComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nieuweLuchthavenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        landComboBox.getAccessibleContext().setAccessibleDescription("");
        landCodeTextField.getAccessibleContext().setAccessibleDescription("Code van het geselecteerde land");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	// ActionListeners
private void naamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naamTextFieldActionPerformed
	luchthavenCodeTextField.requestFocusInWindow();
}//GEN-LAST:event_naamTextFieldActionPerformed

private void luchthavenCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchthavenCodeTextFieldActionPerformed
	jaButton.requestFocusInWindow();
}//GEN-LAST:event_luchthavenCodeTextFieldActionPerformed

private void jaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaButtonActionPerformed
	try
	{
		myController.werkPlaats(true);
	}
	catch (LuchthavenException lhe)
	{
		
	}
	okButton.requestFocusInWindow();
}//GEN-LAST:event_jaButtonActionPerformed

private void neeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neeButtonActionPerformed
	try
	{
		myController.werkPlaats(false);
	}
	catch (LuchthavenException lhe)
	{
		
	}
	okButton.requestFocusInWindow();
}//GEN-LAST:event_neeButtonActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		try
		{
			myController.land(landen.get((String) landComboBox.getSelectedItem()));
			myController.naam(naamTextField.getText());
			myController.code(luchthavenCodeTextField.getText());
			myController.werkPlaats(jaButton.isSelected());
			myController.ok();//GEN-LAST:event_okButtonActionPerformed
		}
		catch (LuchthavenException ex)
		{
			Logger.getLogger(RegLuchthavenFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
}                                        

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	myController.cancel();
}//GEN-LAST:event_cancelButtonActionPerformed

private void landComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landComboBoxActionPerformed
	myController.land(landen.get((String)landComboBox.getSelectedItem()));
	naamTextField.requestFocusInWindow();
}//GEN-LAST:event_landComboBoxActionPerformed

private void naamTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_naamTextFieldFocusLost
	myController.land(landen.get((String)landComboBox.getSelectedItem()));
	try
	{
		myController.naam(naamTextField.getText());
	}
	catch (LuchthavenException lhe)
	{
		
	}
}//GEN-LAST:event_naamTextFieldFocusLost

private void luchthavenCodeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_luchthavenCodeTextFieldFocusLost
	try
	{
		myController.code(luchthavenCodeTextField.getText());
	}
	catch (LuchthavenException lhe)
	{
		
	}
}//GEN-LAST:event_luchthavenCodeTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JRadioButton jaButton;
    private javax.swing.ButtonGroup jaNeeButtonGroup;
    private javax.swing.JLabel landCodeLabel;
    private javax.swing.JTextField landCodeTextField;
    private javax.swing.JComboBox landComboBox;
    private javax.swing.JLabel landLabel;
    private javax.swing.JTextField luchthavenCodeTextField;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JTextField naamTextField;
    private javax.swing.JRadioButton neeButton;
    private javax.swing.JPanel nieuweLuchthavenPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel werkPlaatsLabel;
    // End of variables declaration//GEN-END:variables

}
